print("\n")
print("\tZed did not code this exercise. \n\tI am writing it for practice and memorization.")
print("\tZed calls this logic.")
print("\tPark calls it logic operators.")

print("NOT")
print("OR")
print("AND")
print("NOT OR")
print("NOT AND")
print("\tPark calls these comparison operators.")
print("!=, not equal")
print("==, are equal")
print("\n")
print('\tThese operators are asking "Is this TRUE?"')
print('\n')

print("NOT")
print("\t not false = TRUE")
print("\t not true  = FALSE")
print("OR")
print("If one of the operands is TRUE then = TRUE.")
print("\ttrue  or true   = TRUE")
print("\ttrue  or false  = TRUE")
print("\tfalse or true   = TRUE")
print("\tfalse or false  = FALSE")
print("AND")
print("If one of the operands is falast the = FALSE")

