print("\n")
print("\tZed did not code this exercise. \n\tI am writing it for practice and memorization.")
print("\tZed calls this logic.")
print("\tPark calls it logic operators.")

print("NOT")
print("OR")
print("AND")
print("NOT OR")
print("NOT AND")
print("\tPark calls these comparison operators.")
print("!=, not equal")
print("==, are equal")
print("\n")
print('\tThese operators are asking "Is this TRUE?"')
print('\n')

print("NOT")
print("\t not false = TRUE")
print("\t not true  = FALSE\n")
print("\t\tOR")
print("If one of the operands is TRUE then = TRUE.")
print("\ttrue  or true   = TRUE")
print("\ttrue  or false  = TRUE")
print("\tfalse or true   = TRUE")
print("\tfalse or false  = FALSE\n")
print("\t\tAND")
print("If one of the operands is false then = FALSE")
print("\ttrue and flase  = False")
print("\ttrue and true   = True")
print("\tfalse and true  = False")
print("\tfalse and flase = False\n")

print("\t\tNOT OR")
print("Both must be false to = TRUE everything else is FALSE")
print("\tnot(true or false  = False")
print("\tnot(true or true   = False")
print("\tnot(false or true  = False")
print("\tnot(false or flase = True\n")

print("\t\tNOT AND")
print("Both must be true to = FALSE")
print("\tnot(true and false) = True")
print("\tnot(true and true)  = False")
print("\tnot(false and true) = True")
print("\tnot(false and false = True\n")

print("\t\t!=")
print("If both things don't match = TRUE")
print("\tif these things (0)!= this over here  (1)   = True")
print("\t1if this (1) != is the same as the other (1) = False")
print("\tif this (1) != this over here    (0)        = True")
print("\tif this (0) != is the same as the other (0)  =False\n")

print("\t\t==")
print("If both things match = TRUE")